name: eperusteet-ai-service
on: [workflow_dispatch, push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ARTIFACT_NAME: eperusteet-ai

jobs:
  build-and-test-eperusteet-ai-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify -B
      - name: Upload eperusteet-ai-service-jar
        uses: actions/upload-artifact@v4
        with:
          name: eperusteet-ai-service-jar
          path: target/eperusteet-ai-service.jar
  build-image:
    needs: [build-and-test-eperusteet-ai-service]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Download eperusteet-ai-service-jar
        uses: actions/download-artifact@v4
        with:
          name: eperusteet-ai-service-jar
      - name: Build Docker Conainer
        shell: bash
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export BASE_IMAGE="baseimage-fatjar-openjdk17:master"
          cp eperusteet-ai-service.jar $DOCKER_BUILD_DIR/artifact/eperusteet-ai.jar
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
